[build]
  # No build command needed for static site
  command = "echo 'Static site - no build required'"

  # Publish directory (root directory)
  publish = "."

[build.environment]
  # Node version for any build processes
  NODE_VERSION = "18"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  # SPA fallback for any missing routes
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Error pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404
